import type { EventQuickViewLabels } from "@/components/events/event-quick-view-modal";

type Translate = (key: string) => string;

export function getEventQuickViewLabels(t: Translate): EventQuickViewLabels {
  return {
    accessibility: t("events.decisionInfo.accessibilityInformation"),
    addToCalendar: t("events.calendarActions.add"),
    attendanceQr: t("events.actions.attendanceQr"),
    cancelRegistration: t("events.actions.cancelMyRegistration"),
    cancelling: t("events.actions.cancelling"),
    capacity: t("events.card.maxParticipants"),
    checkedIn: t("events.registration.checkedIn"),
    close: t("common.close"),
    cost: t("events.practicalDetails.cost"),
    costNotes: t("events.practicalDetails.costNotes"),
    dateTime: t("events.formGroups.dateTime"),
    description: t("events.form.description"),
    downloadCalendarFile: t("events.calendarActions.download"),
    eventQuickView: t("events.quickView.title"),
    eligibility: t("events.decisionInfo.eligibility"),
    experienceLevel: t("events.decisionInfo.experienceLevel"),
    expectedCommitment: t("events.practicalDetails.expectedCommitment"),
    hostedBy: t("events.card.hostedBy"),
    googleCalendar: t("events.calendarActions.google"),
    joinEvent: t("events.actions.join"),
    joining: t("events.actions.joining"),
    location: t("events.card.location"),
    noDescription: t("events.detail.noDescription"),
    noLimit: t("events.capacity.noLimit"),
    permission: t("events.card.permission"),
    permissionNote: t("events.permission.note"),
    permissionRequired: t("events.permission.required"),
    practicalDetails: t("events.formGroups.practicalDetails"),
    participationInformation: t("events.formGroups.whoCanAttend"),
    registration: t("events.card.registration"),
    registrationFull: t("events.quickView.registrationFull"),
    registeredSuggestion: t("events.calendarActions.registeredSuggestion"),
    riskLevel: t("events.form.riskLevel"),
    responsibleAdult: t("events.decisionInfo.responsibleAdult"),
    requiredMaterials: t("events.practicalDetails.requiredMaterials"),
    safety: t("events.card.safety"),
    sharedEvent: t("events.sharing.sharedEvent"),
    spacesRemaining: t("events.quickView.spacesRemaining"),
    viewEvent: t("events.quickView.viewEvent"),
    viewFullDetails: t("events.quickView.viewFullDetails"),
  };
}
